name: frame_teleprompter
description: "Simple teleprompter for Frame"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  logging: ^1.2.0
  simple_frame_app: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/frame_app.min.lua
